os:
  - linux
  - osx

language: python

python:
  - '2.6'
  - '2.7'
  - '3.0'
  - '3.1'
  - '3.2'
  - '3.3'
  - '3.4'

env:
  matrix:
    # one build with and without numpy support (opt numpy out)
    - NUMPY="--install-option=--disable-numpy"
    - NUMPY=""

before_install:
  - sudo apt-get install -qq ant

install:
  - pip install . $NUMPY
  - pip install -r test-requirements.txt
  - ant -f test/build.xml

script:
  - python -c "import jpype"
  - python test/testsuite.py
